INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_PSCR_LMR2LTE PSCR_LMR2LTE)

FIND_PATH(
    PSCR_LMR2LTE_INCLUDE_DIRS
    NAMES PSCR_LMR2LTE/api.h
    HINTS $ENV{PSCR_LMR2LTE_DIR}/include
        ${PC_PSCR_LMR2LTE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    PSCR_LMR2LTE_LIBRARIES
    NAMES gnuradio-PSCR_LMR2LTE
    HINTS $ENV{PSCR_LMR2LTE_DIR}/lib
        ${PC_PSCR_LMR2LTE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/PSCR_LMR2LTETarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PSCR_LMR2LTE DEFAULT_MSG PSCR_LMR2LTE_LIBRARIES PSCR_LMR2LTE_INCLUDE_DIRS)
MARK_AS_ADVANCED(PSCR_LMR2LTE_LIBRARIES PSCR_LMR2LTE_INCLUDE_DIRS)
